# Generated by Django 6.0.3 on 2026-05-07 12:07

from django.db import migrations

def backfill_collections(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Collection = apps.get_model('rag', 'Collection')
    Document = apps.get_model('rag', 'Document')
    ChatConversation = apps.get_model('rag', 'ChatConversation')

    for user in User.objects.all():
        # Create a Default collection for each user
        collection, created = Collection.objects.get_or_create(
            user=user,
            name="Default",
            defaults={'description': 'Default user collection'}
        )
        
        # Update all documents belonging to this user
        Document.objects.filter(user=user, collection__isnull=True).update(collection=collection)
        
        # Update conversations via document relation, or user if document not available
        ChatConversation.objects.filter(user=user, collection__isnull=True).update(collection=collection)

class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0003_document_page_count_documentchunk_page_number_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_collections, reverse_code=migrations.RunPython.noop),
    ]
