# Generated by Django 6.0.3 on 2026-05-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0005_alter_chatconversation_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatconversation",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="rag.collection",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="rag.collection",
            ),
        ),
    ]
